# Numpy Demo Code

### Imports
Don't forget to do pip install numpy in your terminal first (if it doesn't work try conda install numpy)

In [1]:
import numpy as np

## Creating Numpy Arrays

In [2]:
# creating NumPy array from python list using np.array() function
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

# these can be multiple dimensions -- just use nested lists!
b = np.array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
print(b)

[1 2 3 4 5 6]
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [3]:
#Instantiate a 1D array containing every value in a specified range
#Here, array c contains every whole number up to 5
c = np.arange(5)
print(c)

# doesnt have to start at 0
d = np.arange(2,5)
print(d)

#(start value, end value, step size)
e = np.arange(2, 5, 0.1)
print(e)

#if we want to use decimals but don't know the step size, it wont work
f = np.arange(2, 5.1)
print(f)

#using linspace(), (start value, end value, number of elements) data is evenly seperated
g = np.linspace(2, 5, 50)
print(g)

[0 1 2 3 4]
[2 3 4]
[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7
 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9]
[2. 3. 4. 5.]
[2.         2.06122449 2.12244898 2.18367347 2.24489796 2.30612245
 2.36734694 2.42857143 2.48979592 2.55102041 2.6122449  2.67346939
 2.73469388 2.79591837 2.85714286 2.91836735 2.97959184 3.04081633
 3.10204082 3.16326531 3.2244898  3.28571429 3.34693878 3.40816327
 3.46938776 3.53061224 3.59183673 3.65306122 3.71428571 3.7755102
 3.83673469 3.89795918 3.95918367 4.02040816 4.08163265 4.14285714
 4.20408163 4.26530612 4.32653061 4.3877551  4.44897959 4.51020408
 4.57142857 4.63265306 4.69387755 4.75510204 4.81632653 4.87755102
 4.93877551 5.        ]


In [4]:
#Instantiate an empty array with a specified shape, in this case (2,3)
#The array is not truly "empty" - it just contains uninitialized values!
h = np.empty((2,3))
print(h)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


In [5]:
#Instantiate an array with a specified shape, and fill every cell with a specified value
#Here, array e is a 2x3 array filled with 7s
i = np.full((2,3), 7)
print(i)

#Similar to np.full, np.zeros creates an array filled with 0s and np.ones creates an array filled with 1s
j = np.zeros((2,3))
print(j)
k = np.ones((2,3))
print(k)

[[7 7 7]
 [7 7 7]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#get data type of each array
[a.dtype,
b.dtype]

[dtype('int32'), dtype('float64')]

In [7]:
# NumPy arrays don't need to be 1-dimensional. They can be 2-dimensional (like a matrix), 
# or even more. Each dimension is called an axis and the shape is a tuple of sizes along each axis.
# a only has 1 axis. b has 2 axes.
[a.shape, b.shape]

[(6,), (2, 3)]

## Slicing and Indexing Arrays

In [8]:
# we can index like a python list... gives us data at index 0
print(a[0])

#we can also get sub-arrays ... gives us data from index 2 inclusive to the end
print(a[:2]) #type is still an array

# You can pass a list (or a NumPy array) as the index to get data from multiple indices.
# gives us data from index 2, 3,and 5
print(a[[1,3,5]]) #creates new array

1
[1 2]
[2 4 6]


In [9]:
# index 0 of axis 0 gives us the first row: [1.1, 2.2, 3.3].
print(b[0])
print(b[0, :]) #prints same thing (0 of axis 0 gives first row, : of axis 1 gives every value)

print(b[:, 1]) # : in axis 0 gives all rows, 1 in axis 1 gives second value. Together gives second value of each row

print([b[0,1], b[0][1]]) # ERROR IN DEMO VIDEO FIXED HERE
# b[0,1] and b[0][1] give same value as each other because 0 in axis 0 gives first row, 1 in axis 1 gives second value
# meanwhile, second value in first list within array b also refers to 2.2

[1.1 2.2 3.3]
[1.1 2.2 3.3]
[2.2 5.5]
[2.2, 2.2]


## Mathematical Calculations using 1 or 2 Arrays

In [10]:
np.random.seed(1) #initializes a random number generator

#let's create two 3x3 matricies filled with random integers in the range [0,10)
x = np.random.randint(0, 10, size = (3,3))
y = np.random.randint(0, 10, size = (3,3))

In [11]:
x

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [12]:
y

array([[9, 2, 4],
       [5, 2, 4],
       [2, 4, 7]])

In [13]:
x + y

array([[14, 10, 13],
       [10,  2,  4],
       [ 3, 11, 13]])

In [14]:
x - y

array([[-4,  6,  5],
       [ 0, -2, -4],
       [-1,  3, -1]])

In [15]:
x * y

array([[45, 16, 36],
       [25,  0,  0],
       [ 2, 28, 42]])

In [16]:
x / y # division

array([[0.55555556, 4.        , 2.25      ],
       [1.        , 0.        , 0.        ],
       [0.5       , 1.75      , 0.85714286]])

In [17]:
x // y # integer division (works like floor)

array([[0, 4, 2],
       [1, 0, 0],
       [0, 1, 0]], dtype=int32)

In [18]:
x ** y # raising to the power to

array([[1953125,      64,    6561],
       [   3125,       0,       0],
       [      1,    2401,  279936]], dtype=int32)

In [19]:
print(np.sum(x)) #sum

print(np.mean(x)) #mean

print(np.std(x)) #standard deviation

41
4.555555555555555
3.235604395235786


In [20]:
# We can even only sum across a single axis 
# (e.g. if we want the sum of each row, we take the sum across the columns (axis 1))
print(np.sum(x, axis = 1))
# will sum across the rows which will output an array of the sums of the columns.
print(np.sum(x, axis = 0))

# same as normal sum because we divide across both axis looks like summing one of the first two results
print(np.sum(x, axis = (0,1)))

[22  5 14]
[11 15 15]
41


## Other Numpy Features
This section includes transpose, magnitude, dot product, matrix product, and max/min of an array

In [21]:
#we can get the transpose of a matrix (columns to rows, rows to columns)
print(x.T)

# get the magnitude (L2 norm) of a vector
print(np.linalg.norm(x[0]))

[[5 5 1]
 [8 0 7]
 [9 0 6]]
13.038404810405298


In [22]:
# get the dot product of two vectors
print(np.dot(x[0], x[1]))

# multiply two matrices
# Need same number of cols for first matrix and rows for second matrix
# Order matters!
print(np.matmul(x, y))

25
[[103  62 115]
 [ 45  10  20]
 [ 56  40  74]]


In [23]:
# index of minimum value in matrix
print(np.argmin(x))
#index of minimum value in each row
print(np.argmin(x, axis = 1))

# minimum value in matrix
print(np.min(x))
# minimum value in each row
print(np.min(x, axis = 1))

4
[0 1 0]
0
[5 0 1]


## Adjusting Array Shape and Dimensionality

In [24]:
# Sometimes our arrays are not in the format we want so we need to restructure them.
# We can use np.reshape() to redistribute the existing array values into a different shape. 
# The new shape must contain the same number of values as the original shape, 
# but it can have a different number of dimensions.
y = np.arange(6)
print(y)

print(np.reshape(y, (2,3))) #Change the shape of y from (6,) to (2,3)

#If you list the size of one dimension as -1, NumPy will determine the appropriate value for you!
#Here, the new shape will be (1,6)
print(np.reshape(y, (-1, 2)))

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
